random_seed: 47
wandb:
  offline: False
  project: "lung-cancer-detection"
artifacts:
  data:
    name: lidc-idri-raw
    version: v1
    type: dataset
    description: "Zipped dataset of all chest CT scans, masks and nodule volumes in npy format, including scan and nodule metadata. Updated with new volume size for nodules."
  train:
    name: lidc-train
    version: v1
    type: dataset
    description: "List of patient IDs included in the training set"
  valid:
    name: lidc-valid
    version: v1
    type: dataset
    description: "List of patient IDs included in the validation set"
  seg_model:
    name: nodule-segmentation-model
    version: v1
    type: model
    description: "Basic UNet for segmenting lung nodules in chest CTs"
data:
  raw_dir: /Volumes/LaCie/data/lung-cancer-detection/lidc-idri/LIDC-IDRI/
  data_dir: /Volumes/LaCie/data/lung-cancer-detection/lidc-idri/processed/
  zip_dir: /Volumes/LaCie/data/lung-cancer-detection/lidc-idri/compressed/
  split_dir: /Volumes/LaCie/data/lung-cancer-detection/lidc-idri/splits/
  cache_dir: /Volumes/LaCie/data/lung-cancer-detection/lidc-idri/cache/
  sample: False
  batch_size: 32
  val_split: 0.2
seg_model:
  features:
    - 32
    - 32
    - 64
    - 128
    - 256
    - 32
  dropout: 0.0
  lr: 0.0001
  norm:
    - instance
    - affine: True
experiment:
  max_epochs: 100
  auto_lr_find: True
  gpus: -1
  auto_select_gpus: True
