random_seed: 47
wandb:
  offline: False
  project: "lung-cancer-detection"
  tags:
    - nodule-segmentation
    - baseline
artifacts:
  seg_data_artifact:
    name: lidc-idri-cts
    version: v1
    description: "Zipped dataset of chest CT scans and masks in npy format, including scan and nodule metadata"
  seg_model_artifact:
    name: nodule-segmentation-model
    version: v1
    type: model
    description: "Basic UNet for segmenting lung nodules in chest CTs"
data:
  raw_dir: /Volumes/LaCie/data/lung-cancer-detection/lidc-idri/LIDC-IDRI/
  data_dir: /Volumes/LaCie/data/lung-cancer-detection/lidc-idri/processed/segmentation/
  zip_dir: /Volumes/LaCie/data/lung-cancer-detection/lidc-idri/processed/segmentation_compressed/
  cache_dir: /Volumes/LaCie/data/lung-cancer-detection/lidc-idri/cache/
  sample_size: False
  batch_size: 32
  val_split: 0.2
seg_model:
  features:
    - 32
    - 32
    - 64
    - 128
    - 256
    - 32
  dropout: 0.0
  lr: 0.0001
  norm:
    - instance
    - affine: True
experiment:
  max_epochs: 100
  auto_lr_find: True
  gpus: -1
  auto_select_gpus: True
