random_seed: 47
wandb:
  offline: False
  project: "lung-cancer-detection"
  tags:
    - nodule-segmentation
    - testing
artifacts:
  seg_data_artifact:
    name: lidc-idri-cts
    version: v0
    type: dataset
    description: "Ten chest CT scans from LIDC-IDRI dataset including metadata"
  seg_model_artifact:
    name: nodule-segmentation-model
    version: v0
    type: model
    description: "Downsized UNet for segmenting lung nodules in chest CTs"
data:
  raw_dir: /Volumes/LaCie/data/lung-cancer-detection/lidc-idri/LIDC-IDRI/
  data_dir: data/test/
  cache_dir: data/cache/
  sample_size: False
  batch_size: 2
  val_split: 0.2
seg_model:
  features:
    - 4
    - 4
    - 8
    - 16
    - 32
    - 4
  dropout: 0.0
  lr: 0.0001
  norm:
    - instance
    - affine: True
experiment:
  max_epochs: 2
  auto_lr_find: True
  gpus: 0
  auto_select_gpus: False
