random_seed: 47
wandb:
  offline: False
  project: "lung-cancer-detection"
  tags:
    - testing
    - nodule-segmentation
data:
  data_dir: ../data/test
  cache_dir: ../data/test/cache
  batch_size: 2
  val_split: 0.2
model:
  features:
    - 4
    - 4
    - 8
    - 16
    - 32
    - 4
  dropout: 0.0
  lr: 0.0001
  norm:
    - instance
    - affine: True
experiment:
  max_epochs: 2
